const portfolioDocument = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Manikant Mishra | Software Engineering Student</title>
<style>
body{margin:0;background:#f5f1e9;color:#10212b;font:16px/1.6 Arial,sans-serif}header{background:#10212b;color:#f5f1e9;padding:18px 5%;position:sticky;top:0;z-index:2}header strong{font-size:18px}nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:8px}a{color:inherit}main{max-width:1100px;margin:auto}section{padding:64px 5%;border-bottom:1px solid #c7c0b4}h1{font-size:clamp(38px,7vw,82px);line-height:.98;max-width:850px;margin:16px 0}h2{font-size:clamp(28px,4vw,52px);line-height:1.05;margin:0 0 24px}h3{font-size:22px;margin-bottom:6px}p{max-width:820px}.eyebrow{color:#e1784d;font:12px monospace;letter-spacing:1px}.hero{min-height:70vh;display:grid;place-items:center}.hero p{color:#5e7075;max-width:760px;font-size:18px}.contact{background:#e1784d}.contact a{display:block;margin:8px 0;font-weight:bold}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.card{padding:22px;border:1px solid #c7c0b4;background:#ebe3d4}.card h3{margin-top:0}.meta{color:#5e7075;font-size:14px}.band{background:#ebe3d4}.dark{background:#10212b;color:#f5f1e9}.dark .meta{color:#c7d0cf}.tags{color:#e1784d;font:14px monospace}.resume-list{display:grid;gap:18px}.resume-item{border-left:4px solid #e1784d;padding-left:16px}.contact-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}footer{padding:20px 5%;font:12px monospace}@media(max-width:700px){section{padding:48px 5%}.grid,.contact-grid{grid-template-columns:1fr}.hero{min-height:auto;padding-top:70px}nav{gap:12px;font-size:12px}header strong{font-size:16px}}
+</style>
</head>
<body>
<header><strong>MM &nbsp; Manikant Mishra</strong><nav><a href="#about">About</a><a href="#skills">Skills</a><a href="#resume">Resume</a><a href="#projects">Projects</a><a href="#activities">Activities</a><a href="#contact">Contact</a></nav></header>
<main>
<section class="hero"><div><p class="eyebrow">CSE STUDENT / FULL-STACK DEVELOPER</p><h1>Building reliable software with curiosity and code.</h1><p>B.Tech Computer Software Engineering student skilled in MERN full-stack development, JavaScript, Java, REST APIs, MongoDB, DSA, and backend development.</p><p><strong>Manikant Mishra</strong><br>+91 9608851517 | Mathura, India | <a href="mailto:manimishra2006@gmail.com">manimishra2006@gmail.com</a></p></div></section>
<section id="about" class="band"><p class="eyebrow">01 / ABOUT</p><h2>Learning by building useful systems.</h2><p>B.Tech Computer Software Engineering student at GLA University, Mathura, focused on full-stack product development, backend engineering, and practical problem solving.</p><div class="grid"><article class="card"><h3>350+</h3><p>LeetCode problems solved through active problem-solving practice.</p></article><article class="card"><h3>90/90</h3><p>Automated tests passed while validating GigArmour.</p></article></div></section>
<section id="skills"><p class="eyebrow">02 / SKILLS</p><h2>Tools for shipping complete products.</h2><div class="grid"><article class="card"><h3>Programming Languages</h3><p>Java, JavaScript, C++, C, SQL</p></article><article class="card"><h3>Database</h3><p>MongoDB, SQL, Oracle SQL Developer</p></article><article class="card"><h3>Frameworks</h3><p>React.js, Express.js, Node.js, MERN Stack</p></article><article class="card"><h3>Version Control &amp; IDE</h3><p>Git, GitHub, Visual Studio Code</p></article><article class="card"><h3>Coursework</h3><p>Data Structures &amp; Algorithms, Object-Oriented Programming, DBMS, Computer Networks, Software Quality Assurance, Cloud Computing</p></article></div></section>
<section id="resume" class="dark"><p class="eyebrow">03 / RESUME</p><h2>Education and practical engineering.</h2><div class="resume-list"><article class="resume-item"><h3>Bachelor of Technology, Computer Software Engineering</h3><p class="meta">GLA University | Mathura, India | Expected 2028</p><p>5th Semester CPI: 7.7</p></article></div></section>
<section id="projects"><p class="eyebrow">04 / PROJECTS</p><h2>Systems built for real workflows.</h2><div class="grid"><article class="card"><h3>GigArmour</h3><p class="tags">MERN Stack | MongoDB | Express.js | React.js | Node.js | REST APIs | JWT | OTP</p><p>Full-stack parametric insurance platform with rider risk assessment, GPS integrity, fraud detection, and insurance workflows.</p><ul><li>JWT authentication, email OTP verification, password reset, role-based access control, logout, and rate limiting.</li><li>Live rider geolocation with OpenStreetMap Nominatim reverse geocoding and dynamic risk-premium logic.</li><li>Authentication, GPS-integrity, risk-premium, and fraud-detection features validated with 90/90 automated tests.</li></ul><a href="https://github.com/Manikant0931">View on GitHub</a></article><article class="card"><h3>DevTinder</h3><p class="tags">MERN Stack | React.js | Node.js | Express.js | MongoDB | REST APIs</p><p>Full-stack developer networking and matching application with REST API workflows and a React frontend connected to a MongoDB-backed backend.</p><a href="https://github.com/Manikant0931/DevTINDER--FRONTEND">View on GitHub</a></article></div></section>
<section id="activities" class="band"><p class="eyebrow">05 / ACHIEVEMENTS</p><h2>Progress beyond the editor.</h2><div class="resume-list"><article class="resume-item"><h3>Guidewire DevTrails University Hackathon 2026</h3><p>Certificate of Participation.</p></article><article class="resume-item"><h3>Problem solving</h3><p>Active LeetCode practice with 350+ problems solved.</p></article><article class="resume-item"><h3>Project validation</h3><p>Validated GigArmour with 90/90 automated tests.</p></article></div><h2 style="margin-top:48px">Certifications</h2><p>Master Data Management for Beginners; JavaScript Course: Unlocking the Power of JS; Guidewire DevTrails University Hackathon 2026; API Testing; Postman Flows - Beginner; MongoDB Basics for Students; Oracle Cloud Infrastructure 2025; Certificate of Participation in Deviation 2025.</p></section>
<section id="contact" class="contact"><p class="eyebrow">06 / CONTACT</p><h2>Let us build something useful.</h2><div class="contact-grid"><a href="mailto:manimishra2006@gmail.com">manimishra2006@gmail.com</a><a href="tel:+919608851517">+91 9608851517</a><a href="https://linkedin.com/in/manikant-mishra-a4b43931/">LinkedIn</a><a href="https://leetcode.com/u/MKM0006/">LeetCode</a><a href="https://github.com/Manikant0931">GitHub</a></div></section>
</main><footer>Manikant Mishra | Software Engineering Student | Mathura, India</footer>
</body>
</html>`;

export default portfolioDocument;
